### ISSUE TITLE
Need to be screen-size friendly.

### ISSUE THREAD

**Issue by PullStackPigDev** [NastyPigz/ghostandcakes#1]
On smaller screens, it's way harder to get points. On bigger screens it's like they don't lose.

**Comment by PullStackPigDev** [comment]
Partly fixed screen issue but zoom issue is still not fixed.

**Comment by NastyPigz** [comment]
Zoom is now strictly disabled.
+ Rich Mobile Support
+ No more vw, vh
+ only px for better math
Chakra UI is pending

**Comment by NastyPigz** [comment]
Update:
- Chakra UI
- Zoom is enabled again and added rich support on Ghost
- Zoom is pending on Cake Invaders
